### ISSUE TITLE
Load data for training a pytorch network

### ISSUE THREAD

**Issue by oym1994** [google-research/rlds#4]
Hi, thanks for your great job.

I want to train a pytorch network using this kind of dataset, my question is how to load data for pytorch training task?

Thanks

**Comment by sabelaraga** [comment]
Hi!
 
You can convert a tf.data.Dataset to a numpy generator using the `tfds.as_numpy` from [here](https://www.tensorflow.org/datasets/api_docs/python/tfds/as_numpy).

**Comment by oym1994** [comment]
Thanks for you kind response! it helps
